
 import java.io.File;
 import java.io.FileNotFoundException;
 import java.util.Scanner;
 
 /**
  * Google code jam problem solver.
  * Template generated by <a href="https://github.com/Faylixe/jammy">Jammy</a> plugin.
  * 
  * @author
  */
 public final class FractilesSolver {
 
 	/** Scanner instance that allows to parse problem input. **/
 	private final Scanner scanner;
 
 	/**
 	 * Default constructor.
 	 * 
 	 * @param scanner Scanner instance that allows to parse problem input. 
 	 */
 	private FractilesSolver(final Scanner scanner) {
 		this.scanner = scanner;
 	}
 
 	/**
 	 * Solve a problem instance using internal
 	 * scanner to retrieve problem input.
 	 */
 	public void solve() {
 		int k = scanner.nextInt();
 		int c = scanner.nextInt();
 		int s = scanner.nextInt();
 		
 		if (k == 1) {
 			System.out.println(1);
 			return;
 		}
 		
 		int ans_no = k + 1 - c;
 		if (ans_no < 1) ans_no = 1;
 		if (s < ans_no) {
 			System.out.println("IMPOSSIBLE");
 		} else {
 			long start = k;
 			int tc = c;
 			if (tc > k) tc = k;
 			for (int i = 2; i < tc; i ++) {
 				start += (long)Math.pow(k, i - 1) * (tc - i);
 			}
 			System.out.print(start);
 			int no = ans_no;
 			no--;
 			while (no > 0) {
 				no--;
 				start--;
 				System.out.print(" " + start);
 			}
 			System.out.println();
 
 //			if (k < 15 && c < 10 && ans_no < 10) {
 //				start--;
 //				int cnt = 0;
 //				for (int i = (int)Math.pow(2, k) - 1; i > 0 && cnt < 100; i--) {
 //					cnt++;
 //					String pattern = String.format("%"+ k +"s", Integer.toBinaryString(i)).replace(' ', '0');
 //					String zpattern = String.format("%"+ k +"s", "0").replace(' ', '0');
 //					
 //					String temp = pattern;
 //					for (int j = 1; j <= c - 1; j++) {
 //						temp = temp.replaceAll("0", zpattern).replaceAll("1", pattern);
 //					}
 //					System.out.println(temp.substring(start, start + ans_no));
 //				}				
 //			}
 		}		
 	}
 
 	/**
 	 * Solver entry point.
 	 * 
 	 * @param args Command line parameters.
 	 * @throws FileNotFoundException If input file could not be parsed.
 	 */
 	public static void main(final String [] args) throws FileNotFoundException {
 		final File file = new File(args[0]);
 		final Scanner scanner = new Scanner(file);
 		final int n = scanner.nextInt();
 		final FractilesSolver solver = new FractilesSolver(scanner);
 		for (int i = 0; i < n; i++) {
 			System.out.print("Case #" + (i + 1) + ": ");
 			solver.solve();
 		}
 		scanner.close();
 	}
 
 }